# Tell Railway this is a Python project in /backend
[build]
builder = "python"

# Install dependencies inside backend folder
command = "pip install -r backend/requirements.txt"

[start]
command = "uvicorn backend.server:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.11"
MONGO_URL ="mongodb+srv://janidukalhara99_db_user:QGRFDV1cn9zoxVki@cluster0.rjhl6me.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
DB_NAME = "portfolio"
