# railway.toml for FastAPI backend
[build]
builder = "python"

[build.env]
# Install dependencies
command = "pip install -r requirements.txt"

[start]
# Run uvicorn with Railway's PORT
command = "uvicorn server:app --host 0.0.0.0 --port $PORT"

[variables]
# Environment variables for MongoDB Atlas
MONGO_URL = "mongodb+srv://janidukalhara99_db_user:QGRFDV1cn9zoxVki@cluster0.rjhl6me.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
DB_NAME = "portfolio"
